

version: "3"

services:

  web:
    image: nginx:1.22
    container_name: "nginx"
    ports:
      - 80:80
    volumes:
      - ./../Web:/var/www/html
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1-fpm
    container_name: "php"
    volumes:
      - ./../Web:/var/www/html
      - ./conf/php.ini:/usr/local/etc/php/php.ini


